apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-rsnq
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0006-tenant/tkrw-pr712-0075-0006-app/devfile-sample-rsnq@sha256:8471461756cf48c4fc0700a258a4d2b394af8636a91befed57d967a9ae83a973
        name: my-nodejs
        resources: {}
status: {}
